# Generated by Django 4.1.1 on 2022-09-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_person_lastname_alter_person_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default=str, max_length=25),
            preserve_default=False,
        ),
    ]
