# Generated by Django 4.1.1 on 2022-10-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_person_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastname',
        ),
        migrations.AddField(
            model_name='person',
            name='dateofbirth',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dlnumber',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
